let scrollblock =
{
    name:"scrollblock",
    type:SCROLLTEXT,
    x:20,
    y:20,
    layoutSpec:{x:4,y:1,fit:false},
    width:400,
    height:200,
    radius:4,
	clip:true,
	textURL:"/Users/robertdodson/Desktop/FILM/FILM.js",
	size:10,
	textColor:gray,
	font:MainFont,
	//fillColor:gray,
	strokeColor:orange,
	textColor:cyan,
	animator0:{value:"scrollamount",amount:-5,min:-5000.0,max:0.0,type:INC},
}
addBlock(scrollblock)
